kind: Service
apiVersion: v1
metadata:
  labels:
    app: kube-tomcat
  name: kube-tomcat
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kube-tomcat
