kind: Service
apiVersion: v1
metadata:
  labels:
    app: redis-cluster
  name: redis-cluster

spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-port
  selector:
    app: redis-cluster
