apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-redis-cluster
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: kube-redis
    spec:
      containers:
      - name: kube-redis
        image: rootww/redis
        env:
          - name: REDIS_RUN_MODE
            value: "cluster"
        volumeMounts:
        - mountPath: /opt/redis/data
          name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
