apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-maven-cache
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-disk-ssd
