apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  name: 127.0.0.1
localAPIEndpoint:
  advertiseAddress: 127.0.0.1
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"
kubernetesVersion: v1.12.0
controlPlaneEndpoint: ""
apiServerExtraArgs:
  authorization-mode: Node,RBAC
  service-node-port-range: 1-65535
dns:
  type: CoreDNS
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
imageRepository: k8s.gcr.io
