apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-tomcat
    spec:
      containers:
      - name: kube-tomcat
        image: rootww/tomcat:8.5.41-jdk8-apline
        volumeMounts:
        - mountPath: /opt/tomcat/webapps
          name: www
      volumes:
      - name: www
        hostPath: 
          path: "/apps/data/tomcat"
      restartPolicy: Always
