apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: rootww/tomcat:8.5.41-jdk8-apline
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /opt/tomcat/webapps
          name: www
      volumes:
      - name: www
        hostPath: 
          path: "/apps/data/tomcat"
      restartPolicy: Always
