kind: Service
apiVersion: v1
metadata:
  labels:
    app: tomcat
  name: tomcat-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
  selector:
    app: tomcat
