kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: es
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: '-Xms3G -Xmx3G'
        - name: ES_NODE_NAME
          value: es
        image: 172.16.12.80:9000/library/elasticsearch:6.8.11
        imagePullPolicy: Always
        name: es
        volumeMounts:
        - mountPath: /opt/elasticsearch/data
          name: es-data
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: alpine:3.6
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        name: elasticsearch-init
      restartPolicy: Always
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data
  annotations:
    volume.beta.kubernetes.io/storage-class: k8s-nfs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
--- 
kind: Service
apiVersion: v1
metadata:
  labels:
    app: es
  name: es-client
spec:
  ports:
  - name: port1
    protocol: TCP
    port: 9200
    targetPort: 9200
  selector:
    app: es