apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-redis
    spec:
      containers:
      - name: kube-redis
        image: rootww/redis
        volumeMounts:
        - mountPath: /opt/redis/data
          name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kube-redis
  name: kube-redis
  namespace: default
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-port
  selector:
    app: kube-redis
