kind: Service
apiVersion: v1
metadata:
  labels:
    app: kube-jumpserver
  name: kube-jumpserver
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
  selector:
    app: kube-jumpserver
