apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-jumpserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-jumpserver
    spec:
      containers:
      - name: kube-jumpserver
        image: jumpserver/jms_all
        env:
        - name: SECRET_KEY
          value: "kuaixiu"
        - name: BOOTSTRAP_TOKEN
          value: "kuaixiu"
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: ""
        - name: DB_NAME
          value: "jumpserver"
        - name: REDIS_HOST
          value: "127.0.0.1"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        volumeMounts:
        - mountPath: /opt/jumpserver/data/media
          name: jumpserver-media
      restartPolicy: Always
      volumes:
        - name: jumpserver-media
          persistentVolumeClaim:
            claimName: jumpserver-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jumpserver-media
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
